
<h1>Hai This is Sample Example for Multi-Module Project Design By Phalcon PHP Framework - This is Backend</h1><br /><br />


<pre><?php print_r($this->aclSetter->getResources()) ?></pre>

<pre><?php print_r(PHALCON_MODE) ?></pre>

<pre><?php print_r($justLibrary) ?></pre>

<pre><?php print_r(\AuthenticationOpns::getLoggedAdminDetails()) ?></pre>

<pre><?php print_r($_SESSION) ?></pre>

<pre><?php print_r($this->inlineRegistry->getValue()) ?></pre>
